from django.db import models

# Create your models here.
class class_table(models.Model):
    class_id = models.CharField(max_length=255, db_collation='utf8_general_ci')
    is_delete = models.IntegerField(default=1)
    number_1=models.CharField(db_column='1', max_length=255, db_collation='utf8mb4_general_ci', blank=True, null=True)
    number_2 = models.CharField(db_column='2', max_length=255, blank=True, null=True)
    number_3 = models.CharField(db_column='3', max_length=255, blank=True, null=True)
    number_4 = models.CharField(db_column='4', max_length=255, blank=True, null=True)
    number_5 = models.CharField(db_column='5', max_length=255, blank=True, null=True)
    number_6 = models.CharField(db_column='6', max_length=255, blank=True, null=True)
    number_7 = models.CharField(db_column='7', max_length=255, blank=True, null=True)
    number_8 = models.CharField(db_column='8', max_length=255, blank=True, null=True)
    number_9 = models.CharField(db_column='9', max_length=255, blank=True, null=True)
    number_10 = models.CharField(db_column='10', max_length=255, blank=True, null=True)
    number_11 = models.CharField(db_column='11', max_length=255, blank=True, null=True)
    number_12 = models.CharField(db_column='12', max_length=255, blank=True, null=True)
    number_13 = models.CharField(db_column='13', max_length=255, blank=True, null=True)
    number_14 = models.CharField(db_column='14', max_length=255, blank=True, null=True)
    number_15 = models.CharField(db_column='15', max_length=255, blank=True, null=True)
    number_16 = models.CharField(db_column='16', max_length=255, blank=True, null=True)
    number_17 = models.CharField(db_column='17', max_length=255, blank=True, null=True)
    number_18 = models.CharField(db_column='18', max_length=255, blank=True, null=True)
    number_19 = models.CharField(db_column='19', max_length=255, blank=True, null=True)
    number_20 = models.CharField(db_column='20', max_length=255, blank=True, null=True)
    number_21 = models.CharField(db_column='21', max_length=255, blank=True, null=True)
    number_22 = models.CharField(db_column='22', max_length=255, blank=True, null=True)
    number_23 = models.CharField(db_column='23', max_length=255, blank=True, null=True)
    number_24 = models.CharField(db_column='24', max_length=255, blank=True, null=True)
    number_25 = models.CharField(db_column='25', max_length=255, blank=True, null=True)
    number_26 = models.CharField(db_column='26', max_length=255, blank=True, null=True)
    number_27 = models.CharField(db_column='27', max_length=255, blank=True, null=True)
    number_28 = models.CharField(db_column='28', max_length=255, blank=True, null=True)
    number_29 = models.CharField(db_column='29', max_length=255, blank=True, null=True)
    number_30 = models.CharField(db_column='30', max_length=255, blank=True, null=True)
    number_31 = models.CharField(db_column='31', max_length=255, blank=True, null=True)
    number_32 = models.CharField(db_column='32', max_length=255, blank=True, null=True)
    number_33 = models.CharField(db_column='33', max_length=255, blank=True, null=True)
    number_34 = models.CharField(db_column='34', max_length=255, blank=True, null=True)
    number_35 = models.CharField(db_column='35', max_length=255, blank=True, null=True)