# Generated by Django 3.2.3 on 2021-10-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotsearch',
            fields=[
                ('rank', models.IntegerField(primary_key=True, serialize=False)),
                ('href', models.CharField(max_length=255)),
                ('title', models.CharField(db_collation='utf8_general_ci', max_length=100)),
            ],
        ),
    ]
