# Generated by Django 3.2.3 on 2021-11-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='class_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(db_collation='utf8_general_ci', max_length=255)),
                ('is_delete', models.IntegerField(default=1, max_length=1)),
                ('number_1', models.CharField(blank=True, db_collation='utf8mb4_general_ci', db_column='1', max_length=255, null=True)),
                ('number_2', models.CharField(blank=True, db_column='2', max_length=255, null=True)),
                ('number_3', models.CharField(blank=True, db_column='3', max_length=255, null=True)),
                ('number_4', models.CharField(blank=True, db_column='4', max_length=255, null=True)),
                ('number_5', models.CharField(blank=True, db_column='5', max_length=255, null=True)),
                ('number_6', models.CharField(blank=True, db_column='6', max_length=255, null=True)),
                ('number_7', models.CharField(blank=True, db_column='7', max_length=255, null=True)),
                ('number_8', models.CharField(blank=True, db_column='8', max_length=255, null=True)),
                ('number_9', models.CharField(blank=True, db_column='9', max_length=255, null=True)),
                ('number_10', models.CharField(blank=True, db_column='10', max_length=255, null=True)),
                ('number_11', models.CharField(blank=True, db_column='11', max_length=255, null=True)),
                ('number_12', models.CharField(blank=True, db_column='12', max_length=255, null=True)),
                ('number_13', models.CharField(blank=True, db_column='13', max_length=255, null=True)),
                ('number_14', models.CharField(blank=True, db_column='14', max_length=255, null=True)),
                ('number_15', models.CharField(blank=True, db_column='15', max_length=255, null=True)),
                ('number_16', models.CharField(blank=True, db_column='16', max_length=255, null=True)),
                ('number_17', models.CharField(blank=True, db_column='17', max_length=255, null=True)),
                ('number_18', models.CharField(blank=True, db_column='18', max_length=255, null=True)),
                ('number_19', models.CharField(blank=True, db_column='19', max_length=255, null=True)),
                ('number_20', models.CharField(blank=True, db_column='20', max_length=255, null=True)),
                ('number_21', models.CharField(blank=True, db_column='21', max_length=255, null=True)),
                ('number_22', models.CharField(blank=True, db_column='22', max_length=255, null=True)),
                ('number_23', models.CharField(blank=True, db_column='23', max_length=255, null=True)),
                ('number_24', models.CharField(blank=True, db_column='24', max_length=255, null=True)),
                ('number_25', models.CharField(blank=True, db_column='25', max_length=255, null=True)),
                ('number_26', models.CharField(blank=True, db_column='26', max_length=255, null=True)),
                ('number_27', models.CharField(blank=True, db_column='27', max_length=255, null=True)),
                ('number_28', models.CharField(blank=True, db_column='28', max_length=255, null=True)),
                ('number_29', models.CharField(blank=True, db_column='29', max_length=255, null=True)),
                ('number_30', models.CharField(blank=True, db_column='30', max_length=255, null=True)),
                ('number_31', models.CharField(blank=True, db_column='31', max_length=255, null=True)),
                ('number_32', models.CharField(blank=True, db_column='32', max_length=255, null=True)),
                ('number_33', models.CharField(blank=True, db_column='33', max_length=255, null=True)),
                ('number_34', models.CharField(blank=True, db_column='34', max_length=255, null=True)),
                ('number_35', models.CharField(blank=True, db_column='35', max_length=255, null=True)),
            ],
        ),
    ]
