# Generated by Django 3.2.3 on 2021-11-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Background_ms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_table',
            name='is_delete',
            field=models.IntegerField(default=1),
        ),
    ]
