# Generated by Django 3.2.3 on 2021-10-10 08:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New_entries',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('email', models.EmailField(default='-', max_length=50)),
                ('gene_name', models.CharField(default='-', max_length=100)),
                ('organism', models.CharField(default='-', max_length=100)),
                ('more', models.CharField(default='-', max_length=500)),
                ('read_sum', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='User_comment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50)),
                ('reference', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=500)),
                ('read_sum', models.IntegerField(default=1)),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(db_collation='utf8_general_ci', max_length=100)),
                ('school', models.CharField(db_collation='utf8_general_ci', max_length=200)),
                ('area', models.CharField(db_collation='utf8_general_ci', max_length=255)),
                ('grade', models.CharField(db_collation='utf8_general_ci', max_length=20)),
                ('student_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_collation='utf8_general_ci', max_length=15)),
                ('email', models.CharField(db_collation='utf8_general_ci', max_length=40)),
                ('class_id', models.CharField(db_collation='utf8_general_ci', max_length=15)),
                ('pin', models.CharField(db_collation='utf8_general_ci', max_length=4)),
                ('password', models.CharField(default=1, max_length=255)),
                ('level', models.IntegerField(default=1)),
                ('last_login_time', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.CharField(db_collation='utf8_general_ci', max_length=100)),
                ('is_delete', models.IntegerField(default=1)),
            ],
        ),
    ]
