# Generated by Django 3.2.3 on 2021-11-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassDir',
            fields=[
                ('origin_class_id', models.CharField(db_collation='utf8_general_ci', max_length=255, primary_key=True, serialize=False)),
                ('class_dir', models.CharField(db_collation='utf8_general_ci', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(db_collation='utf8_general_ci', max_length=255)),
                ('name', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=255, null=True)),
                ('age', models.IntegerField(blank=True, default=18, null=True)),
                ('email', models.CharField(db_collation='utf8_general_ci', max_length=40)),
                ('pin', models.CharField(db_collation='utf8_general_ci', max_length=4)),
                ('password', models.CharField(max_length=255)),
                ('level', models.IntegerField(default=1)),
                ('origin_user_id', models.CharField(db_collation='utf8_general_ci', max_length=255)),
                ('origin_class_id', models.CharField(db_collation='utf8_general_ci', max_length=255)),
                ('is_delete', models.IntegerField(default=0)),
                ('last_login_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
