# Generated by Django 3.2.3 on 2021-11-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Official_ws', '0002_alter_usertable_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='age',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
